### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by YYsmith** [EadCat/APAP-Image-Stitching#1]
Thanks for your work! when I run the code in some samples, it will get the error: 'ValueError: Sample larger than population or is negative'. The last code executed is ‘final_src, final_dst = ransac.thread(src_match, dst_match, self.opt.ransac_max)’. Could you please give me a solution? Thanks you very much.

**Comment by czy2134** [comment]
Hi, it's a nice code.
I am a beginner who is learning image-stitching.
I don't know how to use the code to calculate the RMSE of image1 and image2.
Could you please write it?
Thanks you very much.
![image](https://user-images.githubusercontent.com/46508512/140475842-57d61f03-0000-41de-9d10-6bf553e74300.png)
