### ISSUE TITLE
there r something i cannot understand

### ISSUE THREAD

**Issue by Dlemand** [EadCat/APAP-Image-Stitching#4]
i am read your excellent  code of  APAP. but i found the  (std_x and std_y) are the same in the red box I painted。could u please tell
me sth about that? thanks

![image](https://user-images.githubusercontent.com/51884893/146012777-8801843b-9858-4a4b-8c47-abad5f388b12.png)

**Comment by EadCat** [comment]
As you said, the code for that part is wrong.

I corrected the part as follows.

<img width="396" alt="right_answer" src="https://user-images.githubusercontent.com/59416168/146159739-daa29a15-380b-41ef-9ec9-a42697836183.png">

Thank you so much.

**Comment by Dlemand** [comment]
> As you said, the code for that part is wrong.
> 
> I corrected the part as follows.
> 
> <img alt="right_answer" width="396" src="https://user-images.githubusercontent.com/59416168/146159739-daa29a15-380b-41ef-9ec9-a42697836183.png">
> 
> Thank you so much.

Thanks for your anwser！
