### ISSUE TITLE
question about Decay weights

### ISSUE THREAD

**Issue by jsjy1** [EadCat/APAP-Image-Stitching#7]
Hello! Thanks for your work! 

` weight = np.exp(-(np.sqrt(dist[:, 0] ** 2 + dist[:, 1] ** 2) * inverse_sigma))`

Is there an extra np.sqrt() here?

**Comment by EadCat** [comment]
Hello.
You're right. According to the formula (8),  np.sqrt is optional(redundant).
In my opinion, however, this is an MSE or RMSE difference(scale difference), not a major part.
Also, due to the problem of scale normalization(related to hyperparameters) in experience, it may have different results.

**Comment by jsjy1** [comment]
Thanks for your reply, now here I understand, and I have a new question.

> Hello. You're right. According to the formula (8), np.sqrt is optional(redundant). In my opinion, however, this is an MSE or RMSE difference(scale difference), not a major part. Also, due to the problem of scale normalization(related to hyperparameters) in experience, it may have different results.

**Comment by jsjy1** [comment]
When performing local transformations, the direct understanding is to mesh SRC, and the points in each mesh share a local transformation array, and each distorted square after the transformation shares a reverse local transformation array (as shown in each green grid in the figure).
![image](https://user-images.githubusercontent.com/88200720/204219584-99cdc44f-dfdf-4a01-8eca-351e704b956c.png)

**Comment by jsjy1** [comment]
But reverse warp is generally used(ensure that all points are mapped), and it does in your code. So the canvas is meshed, 
and each regular small square in the canvas corresponds to a local transformation array (as shown in the figure).
That is, the grid of the image after warp is regular, while the mesh before warp is distorted.

![image](https://user-images.githubusercontent.com/88200720/204220570-11099c58-c461-4db1-ab79-0773388736e8.png)

**1.Am I right to understand that？**

**Comment by jsjy1** [comment]
> This is the warped SRC in the canvas, and each adjacent point with the same pixel value in the figure corresponds to the same local transformation array

**Comment by EadCat** [comment]
Well, According to the code, I divided the source image regularly into the meshes and warp the superpixels using the calculated local homography.
Therefore, the results is warped by local homography.
And I guess that you visualized the warped source(warped by local homographies) and divided it into the regular meshes.
I'm not sure your way, It is just a guessing.
Your visualization is interesting.

**Comment by jsjy1** [comment]
> 
Aha? In this diagram, I just visualized the meshing in your code.=。=
And doesn't the next line of your code indicate the mesh of the canvas instead of the source image? =。=

`mesh = get_mesh((final_w, final_h), mesh_size + 1)`

**Comment by jsjy1** [comment]
> 

Doesn't "final_xx" indicate the size of the canvas?

**Comment by EadCat** [comment]
As you konw, Since the transformation is processed by **the inverse homography**, I think that mesh visualization should be on the source image.

![src_homography](https://user-images.githubusercontent.com/59416168/204241345-946f64dc-ede1-4c96-bca7-ac280f6cccd3.PNG)

This is just my way of implementation and I would appreciate it if you could show me the APAP code that warps from source to target in Python.

**Comment by EadCat** [comment]
My description above should be fixed. right?

**Comment by jsjy1** [comment]
> My description above should be fixed. right?

Sorry, I can't understand I can't understand this sentence.

**Comment by EadCat** [comment]
> Well, According to the code, I divided the source image regularly into the meshes and warp the superpixels using the calculated local homography. Therefore, the result is warped by local homography. And I guess that you visualized the warped source(warped by local homographies) and divided it into the regular meshes. I'm not sure your way, It is just a guessing. Your visualization is interesting.

I mean this description.

**Comment by jsjy1** [comment]
> My description above should be fixed. right?
=.=What does ”fixed“ mean？

**Comment by jsjy1** [comment]
> As you know, Since the transformation is processed by **the inverse homography**, I think that mesh visualization should be on the source image.
> 
> ![src_homography](https://user-images.githubusercontent.com/59416168/204241345-946f64dc-ede1-4c96-bca7-ac280f6cccd3.PNG)
> 
> This is just my way of implementation and I would appreciate it if you could show me the APAP code that warps from source to target in Python.

Yes, I agree with your statement. And I can't write APAP code that warps from source to target.

**Comment by EadCat** [comment]
> > My description above should be fixed. right?
> > =.=What does ”fixed“ mean？

never mind about this.

**Comment by jsjy1** [comment]
I probably got it! Thanks for your answer!
