### ISSUE TITLE
Can it stitch images in horizontal and vertical directions both.

### ISSUE THREAD

**Issue by ceyxasm** [EadCat/APAP-Image-Stitching#8]
I am working on multiple image stitching where my image is images taken from drone and I need to stitch to create a map.
However, most of the implementations i saw can only stitch dominantly in one orientation.

**Comment by EadCat** [comment]
Hi.
I think it can stitch both vertical and horizontal aligned inputs.
Please refer to "./images/demo3/results/out_00000.jpg" & "./images/demo1/results/out_00002.jpg".
However, the success of the task depends on your good placement of adjacent images and the difficulty of stitching itself.

The difficulty of stitching is related to the following factors.
https://github.com/EadCat/APAP-Image-Stitching/issues/1#issuecomment-951160494

**Comment by EadCat** [comment]
When real-time stitching is performed through a drone, this code is unsuitable because it uses Python's single threading.

**Comment by ChenJunzhi-buaa** [comment]
> When real-time stitching is performed through a drone, this code is unsuitable because it uses Python's single threading.

Do you know any good codes or methods for  real-time stitching，Thank you！

**Comment by EadCat** [comment]
Many stitching codes are not open, and there are various algorithms that assume various forms of data(Fixed view or View-free images).
All in all, the classical methods require **energy optimization processes** at each inference, therefore learning-based methods could be a good start if you need a real-time stitching method.
However, the learning-based methods can be limited in use due to the difficulty of building datasets.

**Comment by ChenJunzhi-buaa** [comment]
> Many stitching codes are not open, and there are various algorithms that assume various forms of data(Fixed view or View-free images). All in all, the classical methods require **energy optimization processes** at each inference, therefore learning-based methods could be a good start if you need a real-time stitching method. However, the learning-based methods can be limited in use due to the difficulty of building datasets.

Thank for your reply! My task is to stitch DaJiang aerial video (the  drone flies at an altitude of 120m) , do you know  methods that can solve it well？

**Comment by EadCat** [comment]
Generally speaking, unsupervised learning-based methods will be easy to use.
Unsupervised Methods:
 - UDIS: [UDIS-tensorflow](https://github.com/nie-lang/UnsupervisedDeepImageStitching)
              [UDIS-pytorch](https://github.com/liudakai2/UnsupDIS-pytorch)
 - [HomoGAN](https://github.com/megvii-research/HomoGAN)

Semi-supervised one:
 - https://github.com/megvii-research/LBHomo

If you're using fixed hardware, you can modify [my code](https://github.com/EadCat/WeaklySupervisedStitchingNetwork) and try it, but requires a calibration process.
