### ISSUE TITLE
Does this work？

### ISSUE THREAD

**Issue by CodeSmoking** [EadCat/APAP-Image-Stitching#9]
Does this work？How can I get him running？

**Comment by EadCat** [comment]
Who is he?

**Comment by CodeSmoking** [comment]
the algorithm of APAP

**Comment by EadCat** [comment]
You can run demo command files and experiment with the images I have set up in advance. Similar to the demo, you can go further with your own settings for your own images.

**Comment by CodeSmoking** [comment]
Click demo directly.bat Is it followed with parameters？

**Comment by EadCat** [comment]
By running .bat files, you can stitch the images I set up in advance.

I recommend running them at an anaconda prompt with an appropriate virtual environment installed.
